### ISSUE TITLE
06/04/2020 - daily released

### ISSUE THREAD

**Issue by fservais-heb** [eschnou/covid19-be#17]
daily releases 06/04/2020 : 420 should be 235: https://epidemio.wiv-isp.be/ID/Documents/Covid19/Derni%c3%a8re%20mise%20%c3%a0%20jour%20de%20la%20situation%20%c3%a9pid%c3%a9miologique.pdf

**Comment by eschnou** [comment]
Oops. Used wrong line indeed. Sorry. Thx for reporting !
